name: CI

on:
  push:
    branches: [ main, feature/primer-test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar pruebas
        run: cd proyecto-pruebas && mvn test

      - name: Instalar k6
        uses: grafana/setup-k6-action@v1

      - name: Ejecutar prueba de performance
        run: k6 run performance/login-test.js